### PR TITLE
cost: store the errors instead of failing

### LINKED ISSUE #17: estimation: Return a list of errors instead of failing the entire process
## Abstract

Failing the entire cost estimation process because of a single failure in retrieving the correct product/price is not the best UX. The failure should be recorded and an error returned, however, all the successful estimates should be returned as well.

## Implementation details

For example, by adding a new field to the `cost.State` struct that holds the failed resources and the error of each, e.g. in a `map[string]error`. As well as a method on `cost.Plan` that can be used to retrieve all the failed resources.

## Suggestions/ideas

This is similar in concept to #12 and could probably be accomplished together.

### PR DESCRIPTION
**Pull request by patrislav**
## Abstract

Whenever a `cost.State` is created using `cost.NewState` function, the previous behaviour was to fail it the first time an error is encountered (e.g. when no product matching the query was found.)

This PR adds a new field on `Component` to store the error. It is used by `cost.NewState` instead of returning the error from the function. The errors can then be read from a `ResourceDiff` by using the `Errors` method.

Closes #17

### CODE REVIEW

**Comment by patrislav** [comment]
Updated to pass the CI

File: cost/state.go [hunk 1]
```diff
@@ -37,17 +43,21 @@ func NewState(ctx context.Context, backend Backend, queries []query.Resource) (*
...
 			prods, err := backend.Product().Filter(ctx, comp.ProductFilter)
 			if err != nil {
-				return nil, err
+				state.addComponent(res.Address, comp.Name, Component{Error: err})
+				continue
 			}
 			if len(prods) < 1 {
-				return nil, fmt.Errorf("product not found")
+				state.addComponent(res.Address, comp.Name, Component{Error: ErrProductNotFound})
+				continue
```
Comment (xescugc) [inline cost/state.go:51]: I see that this is not validated anywhere no? Before it was stopping and not it continues but does not report the `Error` no?

I'm missing something maybe.

Comment (patrislav) [reply cost/state.go:51]: The error is stored in the resource with `addComponent` (in the `Error` property of `Component`). The library user can then iterate over the resources and check the `Error` for each of them separately so that if one resource fails, the result is still returned.
